#!/bin/bash

IFS="+" read USER ENV <<< "${USER:?}"
ENV="${ENV:-$USER}"

# The path relative to the host Docker machine where data will be persisted, used
# for adjusting paths when nesting containers
HOST_DATA="${HOST_DATA:?}"

# This is where users environments will be stored
USER_ROOT="${USER_ROOT:-/data/users/$USER}"

ENV_IMAGE="$USER/$ENV"

data-init() {
  mkdir -p $(readlink -f "${USER_ROOT}/..")
  cp /bin/envcmd /data/.envcmd
}

user-init() {
  if [[ ! -d "$USER_ROOT" ]]; then
    mkdir -p "$USER_ROOT"
    mkdir -p "$USER_ROOT/envs"
    mkdir -p "$USER_ROOT/home"
    cp -R /tmp/data/root "$USER_ROOT/root"
  fi
}

env-init() {
  if [[ ! -d "$USER_ROOT/envs/$ENV" ]]; then
    cp -R /tmp/data/env "$USER_ROOT/envs/$ENV"
  fi
  env-docker
  cd "$USER_ROOT/envs/$ENV"
  if ! docker history $ENV_IMAGE &> /dev/null; then
    echo "Building environment ... "
    docker build -t $ENV_IMAGE . &> /dev/null
  fi
}

env-docker() {
  mkdir -p "$USER_ROOT/envs/$ENV/run"
  if ! docker diff "$USER.$ENV" &> /dev/null; then
    docker run -d --privileged \
      --name "$USER.$ENV" \
      --hostname "$ENV" \
      --env PORT=2375 \
      --restart always \
      --volume "$HOST_DATA/users/$USER/envs/$ENV/run:/var/run" \
      jpetazzo/dind > /dev/null
  fi
}

env-session() {
  local session="$USER.$(date +%s)"
  local status="128"
  set +e
  while [[ "$status" == "128" ]]; do
    if [[ -f "$USER_ROOT/root/$session" ]]; then
      read cmd args <<< "$(cat $USER_ROOT/root/$session)"
      case "$cmd" in
      *rebuild)
        docker build -t "$ENV_IMAGE" .
        ;;
      *switch)
        echo "Switching to $args ... "
        ENV="$args"
        env-init
        ;;
      *commit)
        echo "Committing to $args ... "
        docker commit "$session" "$ENV_IMAGE" > /dev/null
        ;;
      esac
      rm -f "$USER_ROOT/root/$session"
    fi
    docker rm -f "$session" &> /dev/null
    docker run -it \
      --name "$session" \
      --net "container:$USER.$ENV" \
      --env "HOSTNAME=$ENV" \
      --env "ENVY_SESSION=$session" \
      --env "ENVY_RANDOM=$RANDOM" \
      --env "DOCKER_HOST=unix:///env/run/docker.sock" \
      --volume "$HOST_DATA/.envcmd:/sbin/reload:ro" \
      --volume "$HOST_DATA/.envcmd:/sbin/rebuild:ro" \
      --volume "$HOST_DATA/.envcmd:/sbin/switch:ro" \
      --volume "$HOST_DATA/.envcmd:/sbin/commit:ro" \
      --volume "$HOST_DATA/users/$USER/envs/$ENV:/env" \
      --volume "$HOST_DATA/users/$USER/root:/root" \
      --volume "$HOST_DATA/users/$USER/home:/home/$USER" \
      --volume "$HOST_DATA:/admin" \
      "$ENV_IMAGE" $(docker-cmd)
    status=$?
  done
  docker rm -f "$session" > /dev/null
  [[ "$status" == "128" ]] || exit "$status"
}

docker-cmd() {
  if [[ "$(docker inspect -f {{.Config.Cmd}} $ENV_IMAGE)" != "<no value>" ]]; then
    return
  fi
  if [[ "$(docker inspect -f {{.Config.Entrypoint}} $ENV_IMAGE)" != "<no value>" ]]; then
    return
  fi
  echo "/bin/sh"
}

main() {
  set -e
  data-init
  user-init
  env-init
  env-session
}

main "$@"
